name: Update Site Daily

on:
  # Executa diariamente às 10:00 UTC (7:00 AM Brasília no horário padrão)
  schedule:
    - cron: '0 10 * * *'
  
  # Permite execução manual do workflow
  workflow_dispatch:

# Configurar timezone para Brasil
env:
  TZ: America/Sao_Paulo

jobs:
  update-site:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Se precisar de alguma dependência específica, adicione aqui
        # pip install requests beautifulsoup4
    
    - name: Get current time in Brazil
      run: |
        echo "CURRENT_TIME=$(TZ=America/Sao_Paulo date +'%Y-%m-%d %H:%M:%S %Z')" >> $GITHUB_ENV
        echo "UPDATE_DATE=$(TZ=America/Sao_Paulo date +'%Y-%m-%d')" >> $GITHUB_ENV
    
    - name: Update playlist videos
      run: |
        echo "🎬 Atualizando playlist de vídeos..."
        # Aqui você pode executar o script Python para atualizar os vídeos
        if [ -f "get_playlist_builtin.py" ]; then
          python get_playlist_builtin.py
        fi
        
        # Ou fazer outras atualizações necessárias
        echo "✅ Playlist atualizada em: $CURRENT_TIME"
    
    - name: Update site metadata
      run: |
        echo "📝 Atualizando metadados do site..."
        
        # Atualizar algum arquivo com timestamp da última atualização
        cat > last_update.txt << EOF
        Última atualização: $CURRENT_TIME
        Atualização automática via GitHub Actions
        EOF
        
        echo "✅ Metadados atualizados"
    
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "📋 Mudanças detectadas:"
          git status --short
        else
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "ℹ️ Nenhuma mudança detectada"
        fi
    
    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        git add .
        git commit -m "🤖 Atualização automática do site - $UPDATE_DATE
        
        - Playlist de vídeos atualizada
        - Metadados atualizados
        - Executado em: $CURRENT_TIME"
        
        git push
        
        echo "✅ Mudanças commitadas e enviadas"
    
    - name: Deploy to GitHub Pages
      if: steps.verify-changed-files.outputs.changed == 'true'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
        force_orphan: true
    
    - name: Notify completion
      run: |
        echo "🎉 Atualização diária concluída!"
        echo "⏰ Próxima execução: amanhã às 10:00 (horário de Brasília)"
        
        if [ "${{ steps.verify-changed-files.outputs.changed }}" == "true" ]; then
          echo "✅ Site atualizado e deployado"
        else
          echo "ℹ️ Nenhuma atualização necessária"
        fi